Hack/main/default/objects/Character__c/Character__c.object-meta.xml
<CustomObject>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hack/main/default/objects/Character__c/fields/Alignment__c.field-meta.xml
<CustomField>
    <fullName>Alignment__c</fullName>
    <label>Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LawfulEvil</fullName>
                <label>Lawful Evil</label>
            </value>
            <value>
                <fullName>LawfulGood</fullName>
                <label>Lawful Good</label>
            </value>
            <value>
                <fullName>LawfulNeutral</fullName>
                <label>Lawful Neutral</label>
            </value>
            <value>
                <fullName>Neutral</fullName>
                <label>True Neutral</label>
            </value>
            <value>
                <fullName>NeutralGood</fullName>
                <label>Neutral Good</label>
            </value>
            <value>
                <fullName>NeutralEvil</fullName>
                <label>Neutral Evil</label>
            </value>
            <value>
                <fullName>ChaoticGood</fullName>
                <label>Chaotic Good</label>
            </value>
            <value>
                <fullName>ChaoticEvil</fullName>
                <label>Chaotic Evil</label>
            </value>
            <value>
                <fullName>ChaoticNeutral</fullName>
                <label>Chaotic Neutral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Hack/main/default/objects/Character__c/fields/Charisma__c.field-meta.xml
<CustomField>
    <fullName>Charisma__c</fullName>
    <label>Charisma</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artificer</fullName>
            </value>
            <value>
                <fullName>Barbarian</fullName>
            </value>
            <value>
                <fullName>Bard</fullName>
            </value>
            <value>
                <fullName>Cleric</fullName>
            </value>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Fighter</fullName>
            </value>
            <value>
                <fullName>Monk</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Sorcerer</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Hack/main/default/objects/Character__c/fields/Constitution__c.field-meta.xml
<CustomField>
    <fullName>Constitution__c</fullName>
    <label>Constitution</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Current_HP__c.field-meta.xml
<CustomField>
    <fullName>Current_HP__c</fullName>
    <label>Current_HP</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Deity__c.field-meta.xml
<CustomField>
    <fullName>Deity__c</fullName>
    <label>Deity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Dexterity__c.field-meta.xml
<CustomField>
    <fullName>Dexterity__c</fullName>
    <label>Dexterity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Intelligence__c.field-meta.xml
<CustomField>
    <fullName>Intelligence__c</fullName>
    <label>Intelligence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Max_Hp__c.field-meta.xml
<CustomField>
    <fullName>Max_Hp__c</fullName>
    <label>Max_Hp</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tiny</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Huge</fullName>
            </value>
            <value>
                <fullName>Gargantuan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Hack/main/default/objects/Character__c/fields/Strength__c.field-meta.xml
<CustomField>
    <fullName>Strength__c</fullName>
    <label>Strength</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/objects/Character__c/fields/Wisdom__c.field-meta.xml
<CustomField>
    <fullName>Wisdom__c</fullName>
    <label>Wisdom</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hack/main/default/classes/CharacterController.cls
public class CharacterController {
    @AuraEnabled(Cacheable=true)
    public static List<Character__c> getChars() {
        List<Character__c> chars =  [
            SELECT Name, Description__c, Charisma__c, Constitution__c, Dexterity__c, 
                   Strength__c, Intelligence__c, Wisdom__c, 
                   Current_HP__c, Max_Hp__c, Height__c, Weight__c,
                   Race__c, Level__c, Size__c, Class__c, Alignment__c, Deity__c
            FROM Character__c
        ];
        system.debug(chars);
        return chars;
    }
    @AuraEnabled(Cacheable=true)
    public static List<Character__c> searchChars(String searchTerm) {
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getChars();
        }
        
        searchTerm = '%' + searchTerm + '%';
        List<Character__c> chars =  [
            SELECT Name, Description__c, Charisma__c, Constitution__c, Dexterity__c, 
                   Strength__c, Intelligence__c, Wisdom__c, 
                   Current_HP__c, Max_Hp__c, Height__c, Weight__c,
                   Race__c, Level__c, Size__c, Class__c, Alignment__c, Deity__c
            FROM Character__c
            WHERE Name LIKE :searchTerm
        ];
        system.debug(chars);
        return chars;
    }
    @AuraEnabled
    public static Character__c updateChar(Id charId, String random) {
        Character__c ch = [SELECT Description__c FROM Character__c WHERE id=:charId];
        ch.Description__c = random;
        update ch;
        return ch;
    }
}